### ISSUE TITLE
Random Memory Exceptions

### ISSUE THREAD

**Issue by EyesightTechnology** [grimfang4/SDL_FontCache#19]
Hi! I'm relatively new at SDL2, and needed a way to display text within my game loop that wouldn't slow it down by allocating new memory every frame. This library (so far) has worked out great!

However, I'm noticing that every once in a while, during a fast game-loop, your library throws an exception. These exceptions are always memory related. (Something like "Unable to access/read location 000DDDDD" or something like that) The confusing part is that they occur at random. Usually, when you get an exception there's a specific cause of the problem. (Like when I click a button, it throws an exception. Or when I move my mouse. Or something.) But in this case, my game loop will be happily speeding along, until out of the blue a memory exception is thrown.

**My Theory:** The game loop is running very fast, (~60FPS, according to my calculations) and sometimes memory is not properly managed properly. Like it gets corrupted or something. **Is that a viable theory? Are there any other things that could be causing seemingly random memory exceptions?** If this _is_ the case, would having some kind of framerate capper in my game loop help?

Thanks for a great library!

**Comment by grimfang4** [comment]
Hey, glad you like it!

Can you send me a code sample that this is happening in?

**Comment by EvilPudding** [comment]
As far as I'm aware, this library is completely synchronous and re-entrant, if input is making the exception appear, then it's probably something from that side, maybe you reallocate some array and keep outdated references.

**Comment by EyesightTechnology** [comment]
Well, I figured it out! (Not sure how, but I did.)
