### ISSUE TITLE
Blended vs Solid Rendering

### ISSUE THREAD

**Issue by SimonDoesGit** [grimfang4/SDL_FontCache#33]
I would like to be able to choose between drawing blended (anti-aliased) or solid (aliased) text in a game I'm working on, but SDL_FontCache only allows for drawing blended text. How could I change it to allow for one to pick one rendering style or the other?

**Comment by grimfang4** [comment]
You may be looking for FC_SetFilterMode() using the FC_FILTER_NEAREST filter value.

**Comment by SimonDoesGit** [comment]
Thank you
