### ISSUE TITLE
Drawing on software renderer

### ISSUE THREAD

**Issue by ManoShu** [grimfang4/SDL_FontCache#4]
When compiling my own code and the test project, while using the software renderer, the fonts are loaded but nothing is shown on screen.
Is there something that is needed to make it work?
I need the software renderer to work because i intent to compile to small, ARM-based devices, and OpenGL isn't always available.

Thanks in advance.

EDIT: Lazy Foo's example on http://lazyfoo.net/tutorials/SDL/16_true_type_fonts/index.php don't work either when changing the renderer to software, so i guess it's something related to SDL itself, maybe there's a workaround about this?

**Comment by ManoShu** [comment]
OK, the problem was on the **SDL_RenderCopyEx** method on the main SDL library and was corrected on latest version on Mercurial

Bug details here https://forums.libsdl.org/viewtopic.php?t=11427&sid=f39c3437b51671facee7ef05b475f5cb

**Comment by grimfang4** [comment]
Great!  Thanks for following up on this.
