### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by AlexanderKotliar** [grimfang4/SDL_FontCache#8]
// unable to print columns with '%':
-                if(FC_GetWidth(font, line_plus_word) > width)
-                if(FC_GetWidth(font, "%s", line_plus_word) > width)

// reference to temp string:
-        const char\* old_filter_mode = SDL_GetHint(SDL_HINT_RENDER_SCALE_QUALITY);
-        char old_filter_mode[16];
-       strcpy(old_filter_mode, SDL_GetHint(SDL_HINT_RENDER_SCALE_QUALITY));

**Comment by grimfang4** [comment]
Thanks, Alexander!  These should be fixed now in 0fdfebae5cacd13a25051d2dfecf7129e9d53e52.
